### ISSUE TITLE
[shadow-bug] segfault error while AppInitSanityChecks 

### ISSUE THREAD

**Issue by ygnkim** [kaistshadow/blockchain-sim#6]
Running bitcoin on shadow results in segmentation fault while executing the AppInitSanityChecks function.

**Comment by ygnkim** [comment]
Resolved by disabling secure_allocator. (Rename all secure_allocator in bitcoin sources into std::allocator)

**Comment by ygnkim** [comment]
Disabling secure_allocator might cause another problem, so i decided to handle this bug more directly.

Currently, I suspect that the std::call_once is not properly handled by shadow emulation.

I found that the segmentation fault occurs during the interception of the std::call_once by shadow preload stuffs. More specifically, std::call_once internally calls pthread_once and it is redirected to shadow preload-related handlers. Then, when the shadow checks the liveness of the worker(worker_isAlive()), segmentation fault is occurred.

The reason why std::call_once is leveraged by secure_allocator is to implement singleton instance that manages memory page pool (bitcoin/src/support/lockedpool.h). 

The backtrace of the segmentation fault error is as follow.
#0  __GI___pthread_getspecific (key=<optimized out>) at pthread_getspecific.c:62
#1  0x0000000000426955 in worker_isAlive () at /home/csrc/hdd/blockchain-sim/shadow/src/main/core/shd-worker.c:58
#2  0x00007f7c42142704 in _doEmulate () at /home/csrc/hdd/blockchain-sim/shadow/src/preload/shd-interposer.c:189
#3  0x00007f7c4214d6a0 in pthread_once (a=0x7f7c42137a48 <LockedPoolManager::init_flag>, b=0x7f7c3af06110 <__once_proxy>)
    at /home/csrc/hdd/blockchain-sim/shadow/src/preload/shd-preload-defs.h:219
#4  0x00007f7c41569bf4 in __gthread_once (__once=0x7f7c42137a48 <LockedPoolManager::init_flag>, __func=0x7f7c3af06110 <__once_proxy>)
    at /usr/include/x86_64-linux-gnu/c++/4.8/bits/gthr-default.h:699
#5  0x00007f7c4157346f in std::call_once<void (&)()> (__once=..., __f=@0x7f7c417efa64: {void (void)} 0x7f7c417efa64 <LockedPoolManager::CreateInstance()>) at /usr/include/c++/4.8/mutex:786
#6  0x00007f7c41570bed in LockedPoolManager::Instance () at /home/csrc/hdd/blockchain-sim/plugins/shadow-plugin-bitcoin/build/bitcoin/src/support/lockedpool.h:215
#7  0x00007f7c417839a1 in secure_allocator<unsigned char>::allocate (this=0x7f7c468a4c70, n=32, hint=0x0)
    at /home/csrc/hdd/blockchain-sim/plugins/shadow-plugin-bitcoin/build/bitcoin/src/support/allocators/secure.h:43
#8  0x00007f7c417824d3 in std::_Vector_base<unsigned char, secure_allocator<unsigned char> >::_M_allocate (this=0x7f7c468a4c70, __n=32) at /usr/include/c++/4.8/bits/stl_vector.h:168
#9  0x00007f7c417a22dc in std::_Vector_base<unsigned char, secure_allocator<unsigned char> >::_M_create_storage (this=0x7f7c468a4c70, __n=32) at /usr/include/c++/4.8/bits/stl_vector.h:181
#10 0x00007f7c417a219c in std::_Vector_base<unsigned char, secure_allocator<unsigned char> >::_Vector_base (this=0x7f7c468a4c70, __n=32, __a=...)
    at /usr/include/c++/4.8/bits/stl_vector.h:136
#11 0x00007f7c417a1f57 in std::vector<unsigned char, secure_allocator<unsigned char> >::vector (this=0x7f7c468a4c70, __n=32, __a=...) at /usr/include/c++/4.8/bits/stl_vector.h:270
#12 0x00007f7c417a1cf7 in ECC_Start () at /home/csrc/hdd/blockchain-sim/plugins/shadow-plugin-bitcoin/build/bitcoin/src/key.cpp:331
#13 0x00007f7c4139e665 in AppInitSanityChecks () at /home/csrc/hdd/blockchain-sim/plugins/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:1178
#14 0x00007f7c41372aee in AppInit (argc=6, argv=0x13b9980) at /home/csrc/hdd/blockchain-sim/plugins/shadow-plugin-bitcoin/build/bitcoin/src/bitcoind.cpp:134
#15 0x00007f7c41373214 in main (argc=6, argv=0x13b9980) at /home/csrc/hdd/blockchain-sim/plugins/shadow-plugin-bitcoin/build/bitcoin/src/bitcoind.cpp:186
#16 0x0000000000437ab3 in _process_executeMain (proc=0x126bfe0) at /home/csrc/hdd/blockchain-sim/shadow/src/main/host/shd-process.c:995
#17 0x00000000004614e2 in pth_spawn_trampoline () at /home/csrc/hdd/blockchain-sim/shadow/src/external/rpth/pth_lib.c:357
#18 0x00007f7c44cae800 in ?? () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by ygnkim** [comment]
This issue should be managed for achieving #1. Since the shadow-injector facilitates the bitcoin mining by wallet-handled operation (with GENERATE packet).
